### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by ghost** [Chora10/Cknife#58]
java版本: openjdk-11.0.6
报错信息:java -jar tools/Cknife/Cknife.jar                   
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true                                                     
Exception in thread "main" java.lang.NoClassDefFoundError: org/pushingpixels/substance/api/fonts/FontPolicy                       
        at java.base/java.lang.Class.forName0(Native Method)     
        at java.base/java.lang.Class.forName(Class.java:398)     
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)                                      
Caused by: java.lang.ClassNotFoundException: org.pushingpixels.substance.api.fonts.FontPolicy                                     
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more

**Comment by Joackk** [comment]
请问你解决了吗？我在wind下正常，在kali下就报这个

**Comment by ghost** [comment]
> 请问你解决了吗？我在风下正常，在kali下就报这个

解决了，用蚁剑或者冰蝎

**Comment by Joackk** [comment]
> > 请问你解决了吗？我在风下正常，在kali下就报这个
> 
> 解决了，用蚁剑或者冰蝎

啊，这直接换软件吗

**Comment by sg552** [comment]
放弃吧。这个软件不好用。 kali下报错， 估计应该是jre环境需要用kali 系统自带的UI风格，然后 jar 的引用没有找到。才报错的。

文档不齐全，界面不友好。

放弃吧。
